SwarmCollvoid:
  holo_robot: false
  wheel_base: 0.25
  
  max_vel_x: 0.5
  max_vel_th: 1.3
  min_vel_x: 0.1
  min_vel_th: 0.2
  min_vel_y: 0.0
  max_vel_y: 0.0
  min_vel_th_inplace: 1.0
  acc_lim_x: 5.0
  acc_lim_y: 5.0
  acc_lim_th: 5.2


  #time_to_holo: 0.4
  min_error_holo: 0.04
  max_error_holo: 0.15

  max_vel_with_obstacles: 0.4
  
  footprint_radius: 0.2 #was 0.17
  xy_goal_tolerance: 0.2
  
  yaw_goal_tolerance: 0.2
  left_pref: 0.04
  sim_period: 0.2
  use_obstacles: true

  orca: true
  clearpath: true
  VO: 1
  use_truncation: true
  convex: false